### ISSUE TITLE
로그인 기능을 리팩토링합니다.

### ISSUE THREAD

**Issue by D0ri123** [D0ri123/foreco#107]
## 📌Feature Issue
> redirect uri가 프론트에서 동적으로 변경 가능하도록 합니다. 
또한 지역 정보를 같이 받을 수 있도록 변경합니다.

## 📝To-do
- [x] 연동 DB 설정 변경
- [x] redirect uri 설정 변경
- [x] request parameter에 지역정보 추가

## ETC
> Nothing
