### ISSUE TITLE
이미지 검색 api 수정

### ISSUE THREAD

**Issue by hoiae** [D0ri123/foreco#132]
## 📌Feature Issue
> 이미지 검색 api 수정
## 📝To-do
- [x] 유니코드로 반환되는 쓰레기 이름을 텍스트로 변경
- [x] 문자열이 아니라 list로 반환
- [x] ai요청 방식 openfeign으로 변경

## ETC
> 작업 관련 이슈 등을 입력해주세요.
