### ISSUE TITLE
DynamoDB 세팅

### ISSUE THREAD

**Issue by D0ri123** [D0ri123/foreco#14]
## 📌Feature Issue
> 학습시킬 이미지 데이터를 저장할 수 있는 noSQL DB(Dynamo DB)를 세팅합니다.
## 📝To-do
- [x] aws Dynamo DB 테이블 생성
- [x] Dynamo DB config 설정
- [x] 이미지 테이블 생성

## ETC
> Dynamo HashKey 지정을 카테고리(String문자열)로 지정해서, 카테고리 하나 당 이미지 url이 하나만 들어가는 이슈가 있습니다.
이미지 엔티티를 다시 재정의할 예정이며, refactoring 을 다음 이슈로 지정하여 바로 진행하려고 합니다.
