### ISSUE TITLE
EC2 배포환경 구성

### ISSUE THREAD

**Issue by D0ri123** [D0ri123/foreco#16]
## 📌Feature Issue
> 배포 스크립트 작성

## 📝To-do
- [x] code deploy agent가 참조할 수 있는 배포 진행 스크립트 추가 (`appspec.yml`)
- [x] WAS를 새롭게 띄우는 스크립트 추가(`run_new_was.sh`)
- [x] 새로 띄운 WAS가 완전히 실행되기까지 health check하는 스크립트 추가(`health_check.sh`)
- [x] nginx 리로드를 통해 포트를 스위칭하는 스크립트 추가(`switch.sh`)
- [x] githubaction 동작 관련 스크립트 파일에 CodeDeploy 작업 정의

## ETC
> Nothing
