### ISSUE TITLE
쓰레기 배출요일 및 시간 조회 기능 구현

### ISSUE THREAD

**Issue by D0ri123** [D0ri123/foreco#26]
## 📌Feature Issue
> 사용자의 위치, 요일에 따른 쓰레기 배출 품목을 조회할 수 있습니다.

## 📝To-do
- [x] 기존의 엔티티 설계에서 필드 추가
- [x] controller 구현
- [x] dto, service, repository 구현
- [x] 기능 관련 예외 처리 구현

## ETC
> 기능은 완전히 구현했으나, 추후 개선해야 하는 문제점 list
- 사용자의 위치 정보를 x좌표, y좌표가 아닌 '시,구,동'으로 입력받고 있다.
서버에서 x좌표, y좌표를 시,구,동으로 처리하는 것이 보안성과 확장성을 가질 수 있다고 한다. geocoding API 사용을 고려하고 있다.
- 쿼리 최적화를 하지 못했다.
