### ISSUE TITLE
무중단 배포 구현

### ISSUE THREAD

**Issue by hoiae** [D0ri123/foreco#73]
## 📌Feature Issue
> github action, nginx, docker를 활용한 무중단 배포를 구현합니다.
## 📝To-do
- [x] 무중단 배포 구현을 위한 github action workflow작성
- [x] docker hub private repository 생성
- [x] ec2 t4.small로 변경
- [x] http -> https변경
## ETC
>
