### ISSUE TITLE
검색결과 조회 기능, AI 모델 결과 반환 기능 구현

### ISSUE THREAD

**Issue by D0ri123** [D0ri123/foreco#92]
## 📌Feature Issue
> 검색 결과를 조회하는 기능 리팩토링 + AI 모델 결과 반환 기능을 구현합니다.

## 📝To-do
- [ ] 검색기능 활용을 Querydsl에서 JPQL로 변환
- [ ] AI 모델 서버 url 입력
- [ ] Swagger 문서 수정

## ETC
> 대회 제출 기간 이슈로 인해, querydsl 빌드 실패 해결에 시간이 들 거 같아서 JPQL로 변환하여 검색기능을 구현합니다.
